---
- hosts: "{{ servers }}"
  become: true
  gather_facts: false

  vars:
    deployment_artifact: ../build/suid
    deployment_name: suid
    deployment_snarked:
    deployment_staged:
    deployment_workdir: /opt/suid
    deployment_ledgers_workdir: /opt/suid
    deployment_service: suid

  roles:
  - staketab.ledgers-deployment
